### ISSUE TITLE
Unable to build the solution immediately after cloning repo

### ISSUE THREAD

**Issue by yannduran** [scrubs767/GitStash#10]
I forked the `scrubs767/GitStash` repository, then cloned my fork to my local machine.

But I found that I was unable to build the solution. All of the references to some of the `TeamExplorer*.dll`'s were broken. The affected projects were `GitStash`, `GitStash.ViewModels`, `GitStash.Test` and `TeamExplorer.Common`.
 
Eventually I discovered that the projects were using some kind of **relative** path that didn't even exist on my machine.

For example:
> `..\..\..\..\..\..\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\w4eo15sr.k2p\Microsoft.TeamFoundation.Controls.dll`

instead of:

> `C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\CommonExtensions\Microsoft
\TeamFoundation\Team Explorer\Microsoft.TeamFoundation.Controls.dll`.

Note not only the non-exisent relataive path, but that there's also been a translation from magical `Common Extensions` folder to the weirdly randomly-named extension folders. 

Option 1: I was working on what I thought was a simple pull request, it seems that there's a process in VS (maybe it's *Merge* or *Rebase*, that seems to change the hint path back to the relative path + weird random extension folder that is causing the current problem.

Option 2: I decided that a Nuget package needs to be created to encapusulate all of the *Team Explorer* assemblies, just like has been done for some 'unofficial' VSSDK Nuget packages. So I've asked for advice from Sam Harwell, who is the createor of the unofficial packages

**Comment by scrubs767** [comment]
At an appointment now, will take a look when I get back, but I thought they
all got replaced with nugget packages, try and run Update-Package in the
package manager Console

On Dec 9, 2016 3:44 PM, "Yann Duran" <notifications@github.com> wrote:

I forked the scrubs767/GitStash repository, then cloned my fork to my local
machine.

But I found that I was unable to build the solution. All of the references
to some of the TeamExplorer*.dll's were broken. The affected projects were
GitStash, GitStash.ViewModels, GitStash.Test and TeamExplorer.Common.

Eventually I discovered that the projects were using some kind of *relative*
path that didn't even exist on my machine.

For example:

..\..\..\..\..\..\Program Files (x86)\Microsoft Visual Studio
14.0\Common7\IDE\Extensions\w4eo15sr.k2p\Microsoft.
TeamFoundation.Controls.dll

instead of:

C:\Program Files (x86)\Microsoft Visual Studio
14.0\Common7\IDE\CommonExtensions\Microsoft
\TeamFoundation\Team Explorer\Microsoft.TeamFoundation.Controls.dll.

Note not only the non-exisent relataive path, but that there's also been a
translation from magical Common Extensions folder to the weirdly
randomly-named extension folders.

Option 1: I was working on what I thought was a simple pull request, it
seems that there's a process in VS (maybe it's *Merge* or *Rebase*, that
seems to change the hint path back to the relative path + weird random
extension folder that is causing the current problem.

Option 2: I decided that a Nuget package needs to be created to
encapusulate all of the *Team Explorer* assemblies, just like has been done
for some 'unofficial' VSSDK Nuget packages. So I've asked for advice from
Sam Harwell, who is the createor of the unofficial packages

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/scrubs767/GitStash/issues/10>, or mute the thread

**Comment by scrubs767** [comment]
Also, I just remembered, I have local only nugget packages used in the new
build, so even if that fixes the team Explorer issue (I use the packages
for all of them) it still won't build. I'll release them when I get home. I
wasn't planning on it because they are still in Flux.....will you be on
glitter later?

**Comment by yannduran** [comment]
Yeah I'll be around. What time zone are you in? I'm in GMT+10 (although we're currently +11 due to daylight saving time). 

The Nuget packages that you're talking about are for the VS SDK. Team Explorer assemblies aren't included.

Don't worry, there's no urgency with this, I mainly created the issue because I thought I had an easy fix for it. When I found that VS was messing with the paths, it made things more complicated.

**Comment by scrubs767** [comment]
Here's how I've worked with it in the past, do a search in the visual
studio directory for teamexplorer.vsix, make a copy and rename it to
something.zip, open it and copy the dll's out, in the solution, remove the
references and remake them using the dll's from the vsix (zip). The only
other issue in building is the three packages I have in a local repository.
If you want send me your email in gitter and I will mail them to you, I
haven't published because they aren't ready yet.

**Comment by yannduran** [comment]
Yeah I'll be around. What time zone are you in? I'm in GMT+10 (although we're currently +11 due to daylight saving time). 

The Nuget packages that you're talking about are for the VS SDK. Team Explorer assemblies aren't included.

Don't worry, there's no urgency with this, I mainly created the issue because I thought I had an easy fix for it. When I found that VS was messing with the paths, it made things more complicated.

**Comment by yannduran** [comment]
Wow, that's a great tip about teamexplorer.vsix. I had no idea that existed. Thanks!
