### ISSUE TITLE
Exception when there isn't a valid git project opened

### ISSUE THREAD

**Issue by scrubs767** [scrubs767/GitStash#11]
The gitstash nav item shouldn't be enabled if there isn't a valid git repo opened

**Comment by yannduran** [comment]
OMG I was literally about the submit an issue for exactly this!

You've probably already seen the error message, but I'll include the one I got here because it includes a path would only be valid on your machine.

![image](https://cloud.githubusercontent.com/assets/2031126/21225752/6aaa5ad2-c326-11e6-9eb8-09a181627ff3.png)

**Comment by yannduran** [comment]
Oh also, following the precedent set by other Git functionality in VS, GitStash shouldn't really just be disabled, it shouldn't be visible if there's no git repo present (same as GitFlow and other built-in Git-related navigation items).

**Comment by scrubs767** [comment]
Fixed in release-1.3
